#!/bin/sh

set -xe

if [ $(id -u) -ne 0 ]; then
    exec sudo $0
    exit 1
fi

cd /opt/stack/octavia/bin/
./create_dual_intermediate_CA.sh

cp dual_ca/etc/octavia/certs/server_ca.key.pem /etc/octavia/certs/private/server_ca.key.pem
cp dual_ca/etc/octavia/certs/client.cert-and-key.pem /etc/octavia/certs/private/client.cert-and-key.pem
cp dual_ca/etc/octavia/certs/server_ca.cert.pem /etc/octavia/certs/server_ca.cert.pem
cp dual_ca/etc/octavia/certs/server_ca-chain.cert.pem /etc/octavia/certs/server_ca-chain.cert.pem
cp dual_ca/etc/octavia/certs/client_ca.cert.pem /etc/octavia/certs/client_ca.cert.pem

systemctl restart devstack@o-cw \
    devstack@o-hk \
    devstack@o-hm

exit 0
