#!/bin/sh

set -x

rsync -av --exclude '.git*' --exclude '.tox' --exclude node_modules /mnt/host/octavia-dashboard/ /opt/stack/octavia-dashboard/

cd /opt/stack/octavia-dashboard
python3 manage.py collectstatic --no-input
python3 manage.py compress

sudo systemctl restart httpd
