#!/bin/sh

set -x

#rsync -a --exclude '.git*' /mnt/host/octavia-tempest-plugin/octavia_tempest_plugin/ /opt/stack/tempest/.tox/tempest/lib/python3.6/site-packages/octavia_tempest_plugin/

cd /opt/stack/tempest/

#tox -evenv-tempest -- pip install -c /opt/stack/requirements/upper-constraints.txt -e /mnt/host/octavia-tempest-plugin
tox -evenv-tempest -- pip install -e /mnt/host/octavia-tempest-plugin
